config/routes.rb
Rails.application.routes.draw do
  root to: 'landing#home'

  resources :recipes, except: [:index, :destroy]

  resources :ingredients, except: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :bigint(8)        not null, primary key
#  slug        :string           not null
#  name        :string           not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
    
    has_many :recipe_step_ingredients
    has_many :recipe_steps, through: :recipe_step_ingredients
    has_many :recipes, through: :recipe_steps
    has_one_attached :profile_image
    
    validates :slug, :name, presence: true
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id              :bigint(8)        not null, primary key
#  slug            :string           not null
#  name            :string           not null
#  description     :text
#  completion_time :float
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Recipe < ApplicationRecord
    extend FriendlyId
    friendly_id :name, use: :slugged
  
    # if recipe is destroyed, then all matching recipe_steps must also be destroyed
    has_many :recipe_steps, dependent: :destroy
    has_many :ingredients, through: :recipe_steps

    has_one_attached :profile_image

    accepts_nested_attributes_for :recipe_steps

    validates :slug, :name, presence: true
end

app/models/recipe_step.rb
# == Schema Information
#
# Table name: recipe_steps
#
#  id          :bigint(8)        not null, primary key
#  recipe_id   :bigint(8)
#  step_number :integer          not null
#  instruction :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class RecipeStep < ApplicationRecord
    belongs_to :recipe
    
    has_many :recipe_step_ingredients
    has_many :ingredients, through: :recipe_step_ingredients

    accepts_nested_attributes_for :recipe_step_ingredients
end

app/models/recipe_step_ingredient.rb
# == Schema Information
#
# Table name: recipe_step_ingredients
#
#  id             :bigint(8)        not null, primary key
#  recipe_step_id :bigint(8)
#  ingredient_id  :bigint(8)
#  amount         :integer
#  amount_unit    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class RecipeStepIngredient < ApplicationRecord
    belongs_to :recipe_step
    belongs_to :ingredient

    accepts_nested_attributes_for :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    def create
        @ingredient = Ingredient.new(ingredient_params)

        # TODO comment out now just to test form submission
        # if @ingredient.save
        #     redirect_to :show
        # else
        #     # TODO set friendly error messages
        #     flash.now[:error] = @ingredient.errors.full_messages
        #     render :new
        # end
    end

    def new
        @recipes = Recipe.all # TODO replace with Elasticsearch/more efficient search
        @ingredient = Ingredient.new
        render :new
    end
    
    def edit
        @ingredient = Ingredient.find(params[:id])
        render :edit
    end
    
    def show
        @ingredient = Ingredient.find(params[:id])
        render :show
    end

    def update
        @ingredient = Ingredient.find(params[:id])
        if @ingredient.update(ingredient_params)
            redirect_to :show
        else
            # TODO set friendly error messages
            flash.now[:error] = @ingredient.errors.full_messages
            render :edit
        end
    end

    private

    def ingredient_params
        params.require(:ingredient).permit(
                :name, 
                :description,
                :profile_image
            )
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
    def home
        render :home
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def create
        @recipe = Recipe.new(recipe_params)
        if @recipe.save
            redirect_to recipe_path(@recipe)
        else
            # TODO set friendly error messages
            flash.now[:error] = @recipe.errors.full_messages
            render json: {}, status: 422
        end
    end

    def new
        @recipe = Recipe.new
        render :new
    end
    
    def edit
        @recipe = Recipe.find(params[:id])
        render :edit
    end
    
    def show
        @recipe = Recipe.find(params[:id])
        render :show
    end

    def update
        @recipe = Recipe.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to :show
        else
            # TODO set friendly error messages
            flash.now[:error] = @recipe.errors.full_messages
            render :edit
        end
    end

    private

    def recipe_params
        params.require(:recipe).permit(
            :name, 
            :description, 
            :completion_time,
            recipe_steps_attributes: [
                :instruction, 
                :step_number,
                recipe_step_ingredients_attributes: [
                    :amount,
                    :amount_unit,
                    ingredient_attributes: [
                        :name, 
                        :description
                    ]
                ]
            ]
        )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
    def form_visibility_class(show_flag)
        if show_flag
            'invisible'
        else
            ''
        end
    end
end

app/views/ingredients/edit.html.erb
<h1>Update the <%= @ingredient.name %> Ingredient</h1>

app/views/ingredients/new.html.erb
<h1>Add a New Ingredient</h1>

<%= form_for :ingredient  do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :description%>
    <%= f.text_area :description %>
    
    <%= f.label :profile_image %>
    <%= f.file_field :profile_image %>

    <%= f.submit %>
<% end %>

app/views/ingredients/show.html.erb
<h1><%= @ingredient.name %></h1>
<p><%= @ingredient.description %></p>
<!-- 
<img src=<%= @ingredient.image_url %> alt=<%= "Delicious #{@ingredient.name.pluralize}" %> />-->

app/views/landing/home.html.erb
<h1>Welcome to Your Next Tasty Adventure!<h1>

<%= link_to 'New Ingredient', new_ingredient_path %>
<%= link_to 'New Recipe', new_recipe_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TastyRecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/edit.html.erb
<h1>Update the <%= @ingredient.name %> Ingredient</h1>

app/views/recipes/new.html.erb
<h1>Add a New Recipe</h1>

<%= javascript_pack_tag 'recipes', 'data-turbolinks-track': 'reload' %>


<%= form_for @recipe, html: {id: 'new_recipe_form'}  do |f| %>
    <section class='new-recipe-information-container'>
        <%= label_tag :name %>
        <%= text_field_tag :name %>

        <%= label_tag :description%>
        <%= text_area_tag :description %>
    </section>

    <%= render partial: 'recipes/shared/recipe_step_instruction', locals: {recipe_form: f, show_partial: true} %>
   
    <%= f.submit %>
<% end %>

app/views/recipes/shared/_ingredient.html.erb
<section class='recipe-step-ingredients-container form_visibility_class(#{local_assigns[:show_partial]})'>
    <%= local_assigns[:recipe_step_form].fields_for RecipeStepIngredient.new do |recipe_step_ingredient |%>
        <%= recipe_step_ingredient.fields_for Ingredient.new do |ingredient| %>
            <%= ingredient.label :name %>
            <%= ingredient.text_field :name %>

            <%= ingredient.label :description %>
            <%= ingredient.text_area :description %>
        <% end %>

        <%= recipe_step_ingredient.label :amount%>
        <%= recipe_step_ingredient.number_field :amount %>

        <%= recipe_step_ingredient.label :amount_unit, 'Unit (g, ml, etc.)' %>
        <%= recipe_step_ingredient.text_field :amount_unit %>
    <% end %>
</section>

app/views/recipes/shared/_recipe_step_instruction.html.erb
<section class=<%= "recipe-step-container form_visibility_class(#{local_assigns[:show_partial]})" %>%>
    <%= local_assigns[:recipe_form].fields_for RecipeStep.new do |recipe_step| %>
        <%= recipe_step.label :instruction %>
        <%= recipe_step.text_area :instruction %>
        
        <%= render partial: 'recipes/shared/ingredient', locals: {recipe_step_form: recipe_step, show_partial: true} %>
    <% end %>
</section>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<p><%= @recipe.description %></p>

<label for='recipe_instructions'>Instructions</label>
<ul id='recipe_instructions'>
    <% @recipe.recipe_steps.each do |recipe_step| %>
        <li class='recipe-instruction-item'><%= recipe_step.instruction %></li>
    <% end %>
</ul>